package com.framework.struts.entity;
// Generated 6/12/2019 01:20:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Struts generated by hbm2java
 */
public class Struts  implements java.io.Serializable {


     private long cosigo;
     private String nombre;
     private Date creacion;
     private String creador;
     private String pais;
     private String descripcion;
     private String licencia;

    public Struts() {
    }

	
    public Struts(long cosigo) {
        this.cosigo = cosigo;
    }
    public Struts(long cosigo, String nombre, Date creacion, String creador, String pais, String descripcion, String licencia) {
       this.cosigo = cosigo;
       this.nombre = nombre;
       this.creacion = creacion;
       this.creador = creador;
       this.pais = pais;
       this.descripcion = descripcion;
       this.licencia = licencia;
    }
   
    public long getCosigo() {
        return this.cosigo;
    }
    
    public void setCosigo(long cosigo) {
        this.cosigo = cosigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getCreacion() {
        return this.creacion;
    }
    
    public void setCreacion(Date creacion) {
        this.creacion = creacion;
    }
    public String getCreador() {
        return this.creador;
    }
    
    public void setCreador(String creador) {
        this.creador = creador;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(String licencia) {
        this.licencia = licencia;
    }




}


